--XCRUD Eliminación de los paquetes
DROP PACKAGE PA_CONTRATO;
DROP PACKAGE PA_JUGADOR;
DROP PACKAGE PA_GERENTE;
DROP PACKAGE PA_EQUIPO;
DROP PACKAGE PA_HINCHA;
DROP PACKAGE PA_PRESTAMO;




