---PAQUETE EQUIPO
CREATE OR REPLACE PACKAGE PK_EQUIPOS
IS
    PROCEDURE consultarJugadoresDelEquipo(C_JUGADORES OUT SYS_REFCURSOR);
    PROCEDURE consultarPartidosDelEquipo(C_PARTIDOS OUT SYS_REFCURSOR);
    PROCEDURE consultarTransferenciasDelEquipo(C_TRANSFERENCIAS OUT SYS_REFCURSOR);
    PROCEDURE consultarPrestamosDelEquipo(C_PRESTAMOS OUT SYS_REFCURSOR);
END PK_EQUIPOS;
/


--PAQUETE GERENTE
CREATE OR REPLACE PACKAGE PK_GERENTE
IS
    PROCEDURE consultarJugadoresDelRepresentante(C_JUGADORES OUT SYS_REFCURSOR);
    PROCEDURE consultarPartidosDelRepresentante(C_PARTIDOS OUT SYS_REFCURSOR);
    PROCEDURE consultarTransferenciasDelRepresentante(C_TRANSFERENCIAS OUT SYS_REFCURSOR);
    PROCEDURE consultarPrestamosDelRepresentante(C_PRESTAMOS OUT SYS_REFCURSOR);
END PK_GERENTE;
/

