-- Implementación de PK_EQUIPOS
CREATE OR REPLACE PACKAGE BODY PK_EQUIPOS
IS
PROCEDURE consultarJugadoresDelEquipo(C_JUGADORES OUT SYS_REFCURSOR) IS
BEGIN
OPEN C_JUGADORES FOR
SELECT * FROM JUGADORES WHERE nombreEquipo = 'NOMBRE_EQUIPO';
END consultarJugadoresDelEquipo;

PROCEDURE consultarPartidosDelEquipo(C_PARTIDOS OUT SYS_REFCURSOR) IS
BEGIN
OPEN C_PARTIDOS FOR
SELECT * FROM PARTIDOS WHERE idPartido IN (SELECT idPartido FROM TIENE_RESULTADOS_DE WHERE nombreEquipo = 'NOMBRE_EQUIPO');
END consultarPartidosDelEquipo;

PROCEDURE consultarTransferenciasDelEquipo(C_TRANSFERENCIAS OUT SYS_REFCURSOR) IS
BEGIN
OPEN C_TRANSFERENCIAS FOR
SELECT * FROM TRANSFERENCIAS WHERE nombreEquipo = 'NOMBRE_EQUIPO';
END consultarTransferenciasDelEquipo;

PROCEDURE consultarPrestamosDelEquipo(C_PRESTAMOS OUT SYS_REFCURSOR) IS
BEGIN
OPEN C_PRESTAMOS FOR
SELECT * FROM PRESTAMOS WHERE nombreEquipo = 'NOMBRE_EQUIPO';
END consultarPrestamosDelEquipo;

END PK_EQUIPOS;
/

-- Implementación de PK_GERENTE

CREATE OR REPLACE PACKAGE BODY PK_GERENTE
IS
PROCEDURE consultarJugadoresDelRepresentante(C_JUGADORES OUT SYS_REFCURSOR) IS
BEGIN
OPEN C_JUGADORES FOR
SELECT * FROM JUGADORES WHERE nombreEquipo = 'NOMBRE_EQUIPO';
END consultarJugadoresDelRepresentante;

PROCEDURE consultarPartidosDelRepresentante(C_PARTIDOS OUT SYS_REFCURSOR) IS
BEGIN
OPEN C_PARTIDOS FOR
SELECT * FROM PARTIDOS WHERE idPartido IN (SELECT idPartido FROM TIENE_RESULTADOS_DE WHERE nombreEquipo = 'NOMBRE_EQUIPO');
END consultarPartidosDelRepresentante;

PROCEDURE consultarTransferenciasDelRepresentante(C_TRANSFERENCIAS OUT SYS_REFCURSOR) IS
BEGIN
OPEN C_TRANSFERENCIAS FOR
SELECT * FROM TRANSFERENCIAS WHERE nombreEquipo = 'NOMBRE_EQUIPO';
END consultarTransferenciasDelRepresentante;
PROCEDURE consultarPrestamosDelRepresentante(C_PRESTAMOS OUT SYS_REFCURSOR) IS
BEGIN
OPEN C_PRESTAMOS FOR
SELECT * FROM PRESTAMOS WHERE nombreEquipo = 'NOMBRE_EQUIPO';
END consultarPrestamosDelRepresentante;

END PK_GERENTE;
/