--DEFINICION DE ROLES

--ROLES:

CREATE ROLE EQUIPOS;
CREATE ROLE GERENTE_DEPORTIVO;

--PERMISOS:

--1. Para 'Equipos':
GRANT EXECUTE ON PK_EQUIPOS TO EQUIPO;
--2. Para 'Gerente':
GRANT EXECUTE ON PK_GERENTE TO GERENTE;